#!/bin/sh
set -eu

APP_USER="${CLIRA_DB_APP_USER:-clira_app}"
APP_PASSWORD="${CLIRA_DB_APP_PASSWORD:-clira_app}"
DB_NAME="${POSTGRES_DB:-clira}"
POSTGRES_USER_NAME="${POSTGRES_USER:-postgres}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER_NAME" --dbname "$DB_NAME" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${APP_USER}') THEN
    EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${APP_USER}', '${APP_PASSWORD}');
  ELSE
    EXECUTE format('ALTER ROLE %I WITH LOGIN PASSWORD %L', '${APP_USER}', '${APP_PASSWORD}');
  END IF;
END
\$\$;

GRANT CONNECT ON DATABASE "${DB_NAME}" TO "${APP_USER}";
GRANT USAGE, CREATE ON SCHEMA public TO "${APP_USER}";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER
  ON ALL TABLES IN SCHEMA public TO "${APP_USER}";
GRANT USAGE, SELECT, UPDATE
  ON ALL SEQUENCES IN SCHEMA public TO "${APP_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "${APP_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "${APP_USER}";
SQL





