import { prisma } from '@/lib/prisma';
import { logger } from '@/lib/logger';

/**
 * Compact summary of the reply generation pipeline's current state for a user.
 * Injected into the executive agent's per-turn context so it knows which
 * threads already have auto-generated reply drafts awaiting review.
 */
export interface ReplyPipelineSnapshot {
  /** Emails with generated drafts that the user hasn't acted on yet. */
  pendingDrafts: Array<{
    from: string;
    subject: string;
    confidenceScore: number;
    receivedAt: Date;
  }>;
  /** Count of emails currently being processed by the reply pipeline. */
  processingCount: number;
}

const PENDING_DRAFTS_LIMIT = 8;

/**
 * Query the reply pipeline state for a given user.
 *
 * Returns a lightweight snapshot: which emails already have auto-generated
 * reply drafts (pending user review) and how many are currently being
 * generated. This is intentionally bounded to avoid prompt bloat.
 */
export async function fetchReplyPipelineSnapshot(
  userId: string,
): Promise<ReplyPipelineSnapshot> {
  try {
    const [pendingEmails, processingCount] = await Promise.all([
      // Emails that have a generated draft but no user feedback yet (the queue)
      prisma.email.findMany({
        where: {
          thread: { userId },
          isSent: false,
          feedback: null,
          generatedDraft: { isNot: null },
        },
        select: {
          from: true,
          subject: true,
          createdAt: true,
          generatedDraft: {
            select: { confidenceScore: true },
          },
        },
        orderBy: { createdAt: 'desc' },
        take: PENDING_DRAFTS_LIMIT,
      }),
      // Emails where reply generation is in-flight
      prisma.email.count({
        where: {
          thread: { userId },
          isSent: false,
          feedback: null,
          generatedDraft: null,
          isProcessing: true,
        },
      }),
    ]);

    return {
      pendingDrafts: pendingEmails.map((e) => ({
        from: e.from,
        subject: e.subject,
        confidenceScore: e.generatedDraft?.confidenceScore ?? 0,
        receivedAt: e.createdAt,
      })),
      processingCount,
    };
  } catch (error) {
    logger.debug('[replyPipelineContext] Failed to fetch pipeline snapshot:', error);
    return { pendingDrafts: [], processingCount: 0 };
  }
}

/**
 * Format the pipeline snapshot into a compact string for the exec agent's
 * per-turn context. Follows the same pattern as `pendingCalendarInstruction`.
 */
export function formatReplyPipelineInstruction(
  snapshot: ReplyPipelineSnapshot,
): string {
  const { pendingDrafts, processingCount } = snapshot;

  if (pendingDrafts.length === 0 && processingCount === 0) {
    return 'No pending auto-generated reply drafts. No replies currently being generated.';
  }

  const parts: string[] = [];

  if (pendingDrafts.length > 0) {
    parts.push(
      `${pendingDrafts.length} email(s) already have auto-generated reply drafts awaiting user review in the Reply Queue:`,
    );
    for (const draft of pendingDrafts) {
      const confidence = Math.round(draft.confidenceScore);
      parts.push(
        `  - From: ${draft.from} | Subject: "${draft.subject}" | Confidence: ${confidence}%`,
      );
    }
    parts.push(
      'Do NOT offer to draft replies from scratch for these emails — drafts already exist. Reuse the existing draft when the user is asking to send or edit it, otherwise direct them to the Reply Queue.',
    );
  }

  if (processingCount > 0) {
    parts.push(
      `${processingCount} email(s) are currently having replies generated by the pipeline.`,
    );
  }

  return parts.join('\n');
}
